### ISSUE TITLE
NoSuchMethodError when trying to generate .ensime

### ISSUE THREAD

**Issue by MarkusA380** [yyadavalli/mill-ensime#1]
Here's the full log:
$ mill -i fun.valycorp.mill.GenEnsime/ensimeConfig
```
Compiling (synthetic)/ammonite/predef/interpBridge.sc
Compiling /home/markus/at-pipedrive-export/build.sc
Exception in thread "main" java.lang.NoSuchMethodError: mill.util.Router$EntryPoint.<init>(Ljava/lang/String;Lscala/collection/Seq;Lscala/Option;ZLscala/Function3;I)V
        at fun.valycorp.mill.GenEnsime$.millDiscover$lzycompute(GenEnsimeImpl.scala:63)
        at fun.valycorp.mill.GenEnsime$.millDiscover(GenEnsimeImpl.scala:63)
        at mill.main.RunScript$.$anonfun$resolveTasks$4(RunScript.scala:144)
        at scala.util.Either.map(Either.scala:350)
        at mill.main.RunScript$.$anonfun$resolveTasks$3(RunScript.scala:131)
        at scala.collection.immutable.List.map(List.scala:283)
        at mill.main.RunScript$.$anonfun$resolveTasks$2(RunScript.scala:130)
        at scala.util.Either.flatMap(Either.scala:338)
        at mill.main.RunScript$.resolveTasks(RunScript.scala:127)
        at mill.main.RunScript$.evaluateTasks(RunScript.scala:188)
        at mill.main.RunScript$.$anonfun$runScript$3(RunScript.scala:62)
        at ammonite.util.Res$Success.flatMap(Res.scala:61)
        at mill.main.RunScript$.runScript(RunScript.scala:61)
        at mill.main.MainRunner.$anonfun$runScript$1(MainRunner.scala:85)
        at mill.main.MainRunner.watchLoop2(MainRunner.scala:53)
        at mill.main.MainRunner.runScript(MainRunner.scala:68)
        at mill.MillMain$.main0(MillMain.scala:139)
        at mill.MillMain$.main(MillMain.scala:27)
        at mill.MillMain.main(MillMain.scala)
```

I have adhered closely to the README file.

**Comment by vic** [comment]
We got this error and fixed by updating the mill dependency to 0.2.6. 

Currently we have this working on a fork (will send a PR later this week)

https://github.com/davoclavo/mill-ensime

You can use it by adding 

```scala
import mill._
interp.repositories() =
  interp.repositories() ++ Seq(coursier.MavenRepository("https://jitpack.io"))

@

import $ivy.`io.github.davoclavo::mill-ensime:0.0.3`

```

at the top of your `build.sc` file, or wait until we send the PR and it gets merged.
